DELETE FROM Toy;
DELETE FROM Child;

DROP TABLE IF EXISTS Toy;
DROP TABLE IF EXISTS Toy;

CREATE TABLE Child (
	ChildId INTEGER NOTNULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Happy INT NOT NULL
);

CREATE TABLE Toy (
	ToyId INTEGER NOTNULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	ToyId INTEGER NOTNULL ,
		FOREIGN KEY(`ChildId`) REFERENCES `Child`(`ChildId`)

);
